{% set name = "snowflake-snowpark-python" %}
{% set version = "1.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  skip: true  # [py<38 or py>312]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
    # Snowpark IR
    - protobuf ==3.20.1  # [py<=310]
    - protobuf ==4.25.3  # [py>310]
    - mypy-protobuf
  run:
    - python
    - setuptools >=40.6.0
    - wheel
    - cloudpickle >=1.6.0,<=3.0.0,!=2.1.0,!=2.2.0
    - snowflake-connector-python >=3.14.0,<4.0.0
    - typing-extensions >=4.1.0,<5.0.0
    - pyyaml
    - protobuf >=3.20,<6
    - python-dateutil
    - tzlocal
  run_constrained:
    # Snowpark pandas
    - modin ==0.32.0

test:
  imports:
    - snowflake.snowpark
    - snowflake.snowpark._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.snowflake.com/
  summary: Snowflake Snowpark for Python
  dev_url: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sfc-gh-lmukhopadhyay
    - sfc-gh-nkumar
    - sfc-gh-jdu
    - sfc-gh-aling
    - sfc-gh-aalam
    - sfc-gh-yixie
    - sfc-gh-mkeller
    - sfc-gh-yuwang
