{% set name = "snowflake-snowpark-python" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # need to use path to build on Jenkins
  path: ../

build:
  number: {{ os.environ.get('SNOWFLAKE_SNOWPARK_PYTHON_BUILD_NUMBER', 0) }}
  skip: True  # [py<38 or win32 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  script_env:
    - SNOWFLAKE_IS_PYTHON_RUNTIME_TEST=1

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python
    - typing-extensions >=4.1.0
    # need to pin libffi because of problems in cryptography.
    # This might no longer hold true but keep it just to avoid it from biting us again
    - libffi <=3.4.4
    - pyyaml

test:
  imports:
    - snowflake
    - snowflake.snowpark

about:
  home: https://github.com/snowflakedb/snowpark-python
  summary: Snowpark Python
