{% set name = "snowflake-snowpark-python" %}
{% set version = "1.31.0" %}
{% set noarch_build = (os.environ.get('SNOWFLAKE_SNOWPARK_PYTHON_NOARCH_BUILD', 'false')) == 'true' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # need to use path to build on Jenkins
  path: ../

build:
  number: {{ os.environ.get('SNOWFLAKE_SNOWPARK_PYTHON_BUILD_NUMBER', 1) }}  # THIS IS JUST FOR SNOWPARK PYTHON v1.31.0
  skip: True  # [py<38 or win32 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  script_env:
    - SNOWFLAKE_IS_PYTHON_RUNTIME_TEST=1
{% if noarch_build %}
  noarch: python
  string: "py39_0"  # [py==39]
  string: "py310_0"  # [py==310]
  string: "py311_0"  # [py==311]
  string: "py312_0"  # [py==312]
{% endif %}

requirements:
  host:
    - python >= 3.9
    - pip
    - setuptools >=40.6.0
    - wheel
    # Snowpark IR
    - protobuf==3.20.1  # [py<=310]
    - protobuf==4.25.3  # [py>310]
    - mypy-protobuf
  run:
    - python >= 3.9
    - cloudpickle >=1.6.0,<=3.0.0,!=2.1.0,!=2.2.0
    - snowflake-connector-python >=3.12.0,<4.0.0
    - typing-extensions >=4.1.0,<5.0.0
    # need to pin libffi because of problems in cryptography.
    # This might no longer hold true but keep it just to avoid it from biting us again
    - libffi <=3.4.4
    - pyyaml
    # Snowpark IR
    - protobuf >=3.20,<6
    - python-dateutil
    - tzlocal
  run_constrained:
    # Snowpark pandas
    - modin==0.32.0

test:
  imports:
    - snowflake
    - snowflake.snowpark

about:
  home: https://github.com/snowflakedb/snowpark-python
  summary: Snowpark Python
