from typing import Any, Optional, Union

from snowflake.snowpark._internal.sp_expressions import (
    CaseWhen as SPCaseWhen,
    Expression as SPExpression,
)
from snowflake.snowpark._internal.sp_types.types_package import (
    LiteralType as LiteralType,
)
from snowflake.snowpark.types import DataType as DataType
from snowflake.snowpark.window import WindowSpec as WindowSpec

class Column:
    expression: Any
    def __init__(self, expr: Union[str, SPExpression]) -> None: ...
    def __getitem__(self, field: Union[str, int]) -> Column: ...
    def __eq__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __ne__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __gt__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __lt__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __ge__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __le__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __add__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __radd__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __sub__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __rsub__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __mul__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __rmul__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __truediv__(
        self, other: Union[Column, SPExpression, LiteralType]
    ) -> Column: ...
    def __rtruediv__(
        self, other: Union[Column, SPExpression, LiteralType]
    ) -> Column: ...
    def __mod__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __rmod__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __pow__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __rpow__(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def between(
        self,
        lower_bound: Union[Column, SPExpression, LiteralType],
        upper_bound: Union[Column, SPExpression, LiteralType],
    ) -> Column: ...
    def bitand(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def bitor(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def bitxor(self, other: Union[Column, SPExpression, LiteralType]) -> Column: ...
    def __neg__(self) -> Column: ...
    def equal_null(self, other: Column) -> Column: ...
    def equal_nan(self) -> Column: ...
    def is_null(self) -> Column: ...
    def is_not_null(self) -> Column: ...
    def __and__(self, other: Column) -> Column: ...
    def __rand__(self, other: Column) -> Column: ...
    def __or__(self, other: Column) -> Column: ...
    def __ror__(self, other: Column) -> Column: ...
    def __invert__(self) -> Column: ...
    def cast(self, to: DataType) -> Column: ...
    def desc(self) -> Column: ...
    def desc_nulls_first(self) -> Column: ...
    def desc_nulls_last(self) -> Column: ...
    def asc(self) -> Column: ...
    def asc_nulls_first(self) -> Column: ...
    def asc_nulls_last(self) -> Column: ...
    def like(self, pattern: Union[Column, str]) -> Column: ...
    def regexp(self, pattern: Union[Column, str]) -> Column: ...
    def collate(self, collation_spec: str) -> Column: ...
    def getName(self) -> Optional[str]: ...
    def as_(self, alias: str) -> Column: ...
    def alias(self, alias: str) -> Column: ...
    def name(self, alias: str) -> Column: ...
    def over(self, window: Optional[WindowSpec] = ...) -> Column: ...

class CaseExpr(Column):
    def __init__(self, expr: SPCaseWhen) -> None: ...
    def when(
        self, condition: Column, value: Union[Column, LiteralType]
    ) -> CaseExpr: ...
    def otherwise(self, value: Union[Column, LiteralType]) -> CaseExpr: ...
    else_: Any
