from typing import Any, Dict

import snowflake.snowpark
from snowflake.snowpark.dataframe import DataFrame
from snowflake.snowpark.types import StructType as StructType

class DataFrameReader:
    session: Any
    def __init__(self, session: snowflake.snowpark.Session) -> None: ...
    def table(self, name: str) -> DataFrame: ...
    def schema(self, schema: StructType) -> DataFrameReader: ...
    def csv(self, path: str) -> DataFrame: ...
    def json(self, path: str) -> DataFrame: ...
    def avro(self, path: str) -> DataFrame: ...
    def parquet(self, path: str) -> DataFrame: ...
    def orc(self, path: str) -> DataFrame: ...
    def xml(self, path: str) -> DataFrame: ...
    def option(self, key: str, value) -> DataFrameReader: ...
    def options(self, configs: Dict) -> DataFrameReader: ...
