from typing import Any, Dict, Union

class Row(tuple):
    def __new__(cls, *values: Any, **named_values: Any): ...
    def __getitem__(self, item: Union[int, str, slice]): ...
    def __setitem__(self, key, value) -> None: ...
    def __getattr__(self, item): ...
    def __setattr__(self, key, value) -> None: ...
    def __contains__(self, item): ...
    def __call__(self, *args, **kwargs): ...
    def __copy__(self): ...
    def __reduce__(self): ...
    def asDict(self, recursive: bool = ...) -> Dict: ...
