class SchemaUtils:
    @staticmethod
    def command_attributes(): ...
    @staticmethod
    def list_stage_attributes(): ...
    @staticmethod
    def remove_state_file_attributes(): ...
    @staticmethod
    def put_attributes(): ...
    @staticmethod
    def get_attributes(): ...
    @staticmethod
    def analyze_attributes(sql: str, session): ...
    @staticmethod
    def random_string(): ...
