from ...parameters import ORACLEDB_CONNECTION_PARAMETERS

host = ORACLEDB_CONNECTION_PARAMETERS["host"]
port = ORACLEDB_CONNECTION_PARAMETERS["port"]
service_name = ORACLEDB_CONNECTION_PARAMETERS["service_name"]
URL = f"jdbc:oracle:thin:@//{host}:{port}/{service_name}"
EXTERNAL_ACCESS_INTEGRATION = "SNOWPARK_DBAPI_ORACLEDB_TEST_INTEGRATION"
