from ...parameters import MONGODB_JDBC_CONNECTION_PARAMETERS

URL = MONGODB_JDBC_CONNECTION_PARAMETERS["uri"]
PASSWORD = MONGODB_JDBC_CONNECTION_PARAMETERS["password"]
USERNAME = MONGODB_JDBC_CONNECTION_PARAMETERS["username"]
EXTERNAL_ACCESS_INTEGRATION = "snowpark_dbapi_mongodb_jdbc_test_integration"
