from decimal import Decimal
import datetime
from snowflake.snowpark import Row
from snowflake.snowpark.types import (
    StructType,
    StructField,
    LongType,
    BooleanType,
    DecimalType,
    DoubleType,
    DateType,
    TimeType,
    TimestampType,
    StringType,
    BinaryType,
    TimestampTimeZone,
)

# XML, GEOMETRY, GEOGRAPHY types are not supported in ODBC driver

SQL_SERVER_TABLE_NAME = "test_db.dbo.ALL_TYPE_TABLE"
SQL_SEVER_UNICODE_TABLE_NAME = "test_db.dbo.用户資料"
SQL_SERVER_TEST_EXTERNAL_ACCESS_INTEGRATION = {
    "external_access_integration": "snowpark_dbapi_sql_server_test_integration"
}
SQL_SERVER_SCHEMA = StructType(
    [
        StructField("ID", LongType(), False),
        StructField("BIGINT_COL", LongType(), True),
        StructField("INT_COL", LongType(), True),
        StructField("SMALLINT_COL", LongType(), True),
        StructField("TINYINT_COL", LongType(), True),
        StructField("BIT_COL", BooleanType(), True),
        StructField("DECIMAL_COL", DecimalType(18, 4), True),
        StructField("NUMERIC_COL", DecimalType(10, 2), True),
        StructField("MONEY_COL", DecimalType(19, 4), True),
        StructField("SMALLMONEY_COL", DecimalType(10, 4), True),
        StructField("FLOAT_COL", DoubleType(), True),
        StructField("REAL_COL", DoubleType(), True),
        StructField("DATE_COL", DateType(), True),
        StructField("TIME_COL", TimeType(), True),
        StructField("DATETIME_COL", TimestampType(TimestampTimeZone("ntz")), True),
        StructField("DATETIME2_COL", TimestampType(TimestampTimeZone("ntz")), True),
        StructField("SMALLDATETIME_COL", TimestampType(TimestampTimeZone("ntz")), True),
        StructField("CHAR_COL", StringType(16777216), True),
        StructField("VARCHAR_COL", StringType(16777216), True),
        StructField("VARCHAR_MAX_COL", StringType(16777216), True),
        StructField("TEXT_COL", StringType(16777216), True),
        StructField("NCHAR_COL", StringType(16777216), True),
        StructField("NVARCHAR_COL", StringType(16777216), True),
        StructField("NVARCHAR_MAX_COL", StringType(16777216), True),
        StructField("NTEXT_COL", StringType(16777216), True),
        StructField("BINARY_COL", BinaryType(), True),
        StructField("VARBINARY_COL", BinaryType(), True),
        StructField("VARBINARY_MAX_COL", BinaryType(), True),
        StructField("IMAGE_COL", BinaryType(), True),
        StructField("UNIQUEIDENTIFIER_COL", StringType(16777216), True),
        StructField("SQL_VARIANT_COL", BinaryType(), True),
        StructField("TIMESTAMP_COL", BinaryType(), False),
    ]
)

SQL_SERVER_UNICODE_SCHEMA = StructType(
    [
        StructField('"編號"', LongType(), nullable=False),
        StructField('"姓名"', StringType(16777216), nullable=True),
        StructField('"國家"', StringType(16777216), nullable=True),
        StructField('"備註"', StringType(16777216), nullable=True),
    ]
)


EXPECTED_TEST_DATA = [
    Row(
        ID=1,
        BIGINT_COL=9223372036854775807,
        INT_COL=2147483647,
        SMALLINT_COL=32767,
        TINYINT_COL=255,
        BIT_COL=True,
        DECIMAL_COL=Decimal("123456.7890"),
        NUMERIC_COL=Decimal("9999.99"),
        MONEY_COL=Decimal("922337203685477.5000"),
        SMALLMONEY_COL=Decimal("214748.3600"),
        FLOAT_COL=1.79e100,
        REAL_COL=3.3999999274014946e20,
        DATE_COL=datetime.date(2023, 1, 15),
        TIME_COL=datetime.time(14, 30, 25),
        DATETIME_COL=datetime.datetime(2023, 1, 15, 14, 30, 25, 123000),
        DATETIME2_COL=datetime.datetime(2023, 1, 15, 14, 30, 25),
        SMALLDATETIME_COL=datetime.datetime(2023, 1, 15, 14, 30),
        CHAR_COL="Sample1   ",
        VARCHAR_COL="Sample VARCHAR 1",
        VARCHAR_MAX_COL="This is a long VARCHAR(MAX) sample text for row 1",
        TEXT_COL="Sample TEXT 1",
        NCHAR_COL="Unicode1  ",
        NVARCHAR_COL="Unicode VARCHAR 1",
        NVARCHAR_MAX_COL="This is a long NVARCHAR(MAX) unicode text for row 1",
        NTEXT_COL="Unicode TEXT 1",
        BINARY_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        VARBINARY_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        VARBINARY_MAX_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef\x01#Eg\x89\xab\xcd\xef"),
        IMAGE_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        UNIQUEIDENTIFIER_COL="3AE71804-5408-450E-B393-4EA521D7F425",
        SQL_VARIANT_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08k"),
    ),
    Row(
        ID=2,
        BIGINT_COL=-9223372036854775808,
        INT_COL=-2147483648,
        SMALLINT_COL=-32768,
        TINYINT_COL=0,
        BIT_COL=False,
        DECIMAL_COL=Decimal("-123456.7890"),
        NUMERIC_COL=Decimal("-9999.99"),
        MONEY_COL=Decimal("-922337203685477.5000"),
        SMALLMONEY_COL=Decimal("-214748.3600"),
        FLOAT_COL=2.23e-100,
        REAL_COL=1.1799999625533166e-20,
        DATE_COL=datetime.date(2023, 2, 20),
        TIME_COL=datetime.time(9, 15, 45),
        DATETIME_COL=datetime.datetime(2023, 2, 20, 9, 15, 45, 457000),
        DATETIME2_COL=datetime.datetime(2023, 2, 20, 9, 15, 45),
        SMALLDATETIME_COL=datetime.datetime(2023, 2, 20, 9, 16),
        CHAR_COL="Test2     ",
        VARCHAR_COL="Test VARCHAR 2",
        VARCHAR_MAX_COL="Another long VARCHAR(MAX) sample text for row 2",
        TEXT_COL="Test TEXT 2",
        NCHAR_COL="测试2       ",
        NVARCHAR_COL="测试 VARCHAR 2",
        NVARCHAR_MAX_COL="Another long NVARCHAR(MAX) unicode text for row 2 with Chinese characters",
        NTEXT_COL="测试 TEXT 2",
        BINARY_COL=bytearray(b"\xfe\xdc\xba\x98vT2\x10"),
        VARBINARY_COL=bytearray(b"\xfe\xdc\xba\x98vT2\x10"),
        VARBINARY_MAX_COL=bytearray(b"\xfe\xdc\xba\x98vT2\x10\xfe\xdc\xba\x98vT2\x10"),
        IMAGE_COL=bytearray(b"\xfe\xdc\xba\x98vT2\x10"),
        UNIQUEIDENTIFIER_COL="9043B413-B91E-4F24-A82E-58D10E1CB1EF",
        SQL_VARIANT_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08o"),
    ),
    Row(
        ID=3,
        BIGINT_COL=1000000000000000,
        INT_COL=1000000,
        SMALLINT_COL=1000,
        TINYINT_COL=128,
        BIT_COL=True,
        DECIMAL_COL=Decimal("0.0001"),
        NUMERIC_COL=Decimal("0.01"),
        MONEY_COL=Decimal("100.5000"),
        SMALLMONEY_COL=Decimal("50.2500"),
        FLOAT_COL=3.14159265,
        REAL_COL=2.718280076980591,
        DATE_COL=datetime.date(2023, 3, 10),
        TIME_COL=datetime.time(18, 45, 30),
        DATETIME_COL=datetime.datetime(2023, 3, 10, 18, 45, 30, 790000),
        DATETIME2_COL=datetime.datetime(2023, 3, 10, 18, 45, 30),
        SMALLDATETIME_COL=datetime.datetime(2023, 3, 10, 18, 45),
        CHAR_COL="Data3     ",
        VARCHAR_COL="Data VARCHAR 3",
        VARCHAR_MAX_COL="Third VARCHAR(MAX) sample with special chars: !@#$%^&*()",
        TEXT_COL="Data TEXT 3",
        NCHAR_COL="データ3      ",
        NVARCHAR_COL="データ VARCHAR 3",
        NVARCHAR_MAX_COL="Third NVARCHAR(MAX) with Japanese: こんにちは世界",
        NTEXT_COL="データ TEXT 3",
        BINARY_COL=bytearray(b"\x11\x11\x11\x11\x11\x11\x11\x11"),
        VARBINARY_COL=bytearray(b'""""""""'),
        VARBINARY_MAX_COL=bytearray(b"33333333DDDDDDDD"),
        IMAGE_COL=bytearray(b"UUUUUUUU"),
        UNIQUEIDENTIFIER_COL="C7F28568-6F34-41B1-97E4-3CF55C57D43C",
        SQL_VARIANT_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08s"),
    ),
    Row(
        ID=4,
        BIGINT_COL=-500000000000000,
        INT_COL=-500000,
        SMALLINT_COL=-500,
        TINYINT_COL=64,
        BIT_COL=False,
        DECIMAL_COL=Decimal("999.9999"),
        NUMERIC_COL=Decimal("999.99"),
        MONEY_COL=Decimal("1000000.0000"),
        SMALLMONEY_COL=Decimal("10000.0000"),
        FLOAT_COL=1.23e50,
        REAL_COL=98700001280.0,
        DATE_COL=datetime.date(2023, 4, 25),
        TIME_COL=datetime.time(12, 0),
        DATETIME_COL=datetime.datetime(2023, 4, 25, 12, 0),
        DATETIME2_COL=datetime.datetime(2023, 4, 25, 12, 0),
        SMALLDATETIME_COL=datetime.datetime(2023, 4, 25, 12, 0),
        CHAR_COL="Record4   ",
        VARCHAR_COL="Record VARCHAR 4",
        VARCHAR_MAX_COL="Fourth record with emojis",
        TEXT_COL="Record TEXT 4",
        NCHAR_COL="Запись4   ",
        NVARCHAR_COL="Запись VARCHAR 4",
        NVARCHAR_MAX_COL="Fourth record with Cyrillic: Привет мир!",
        NTEXT_COL="Запись TEXT 4",
        BINARY_COL=bytearray(b"\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa"),
        VARBINARY_COL=bytearray(b"\xbb\xbb\xbb\xbb\xbb\xbb\xbb\xbb"),
        VARBINARY_MAX_COL=bytearray(
            b"\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd"
        ),
        IMAGE_COL=bytearray(b"\xee\xee\xee\xee\xee\xee\xee\xee"),
        UNIQUEIDENTIFIER_COL="32E648D8-BFBE-4419-A478-07C7AE897FC4",
        SQL_VARIANT_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08w"),
    ),
    Row(
        ID=5,
        BIGINT_COL=7777777777777777,
        INT_COL=777777,
        SMALLINT_COL=7777,
        TINYINT_COL=200,
        BIT_COL=True,
        DECIMAL_COL=Decimal("0.0000"),
        NUMERIC_COL=Decimal("0.00"),
        MONEY_COL=Decimal("-50.7500"),
        SMALLMONEY_COL=Decimal("-25.2500"),
        FLOAT_COL=0.0,
        REAL_COL=0.0,
        DATE_COL=datetime.date(2023, 5, 30),
        TIME_COL=datetime.time(23, 59, 59),
        DATETIME_COL=datetime.datetime(2023, 5, 31, 0, 0),
        DATETIME2_COL=datetime.datetime(2023, 5, 30, 23, 59, 59),
        SMALLDATETIME_COL=datetime.datetime(2023, 5, 30, 23, 59),
        CHAR_COL="Final5    ",
        VARCHAR_COL="Final VARCHAR 5",
        VARCHAR_MAX_COL="Last record with symbols",
        TEXT_COL="Final TEXT 5",
        NCHAR_COL="最終5       ",
        NVARCHAR_COL="最終 VARCHAR 5",
        NVARCHAR_MAX_COL="Last record with mixed scripts",
        NTEXT_COL="最終 TEXT 5",
        BINARY_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x00\x00"),
        VARBINARY_COL=bytearray(b"\xff\xff\xff\xff\xff\xff\xff\xff"),
        VARBINARY_MAX_COL=bytearray(
            b"\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e"
        ),
        IMAGE_COL=bytearray(b"\x99\x99\x99\x99\x99\x99\x99\x99"),
        UNIQUEIDENTIFIER_COL="384A86A8-5DF5-4AEC-8688-4C9BCBA26592",
        SQL_VARIANT_COL=bytearray(b"\x01#Eg\x89\xab\xcd\xef"),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08{"),
    ),
    Row(
        ID=6,
        BIGINT_COL=None,
        INT_COL=None,
        SMALLINT_COL=None,
        TINYINT_COL=None,
        BIT_COL=None,
        DECIMAL_COL=None,
        NUMERIC_COL=None,
        MONEY_COL=None,
        SMALLMONEY_COL=None,
        FLOAT_COL=None,
        REAL_COL=None,
        DATE_COL=None,
        TIME_COL=None,
        DATETIME_COL=None,
        DATETIME2_COL=None,
        SMALLDATETIME_COL=None,
        CHAR_COL=None,
        VARCHAR_COL=None,
        VARCHAR_MAX_COL=None,
        TEXT_COL=None,
        NCHAR_COL=None,
        NVARCHAR_COL=None,
        NVARCHAR_MAX_COL=None,
        NTEXT_COL=None,
        BINARY_COL=None,
        VARBINARY_COL=None,
        VARBINARY_MAX_COL=None,
        IMAGE_COL=None,
        UNIQUEIDENTIFIER_COL=None,
        SQL_VARIANT_COL=bytearray(b""),
        TIMESTAMP_COL=bytearray(b"\x00\x00\x00\x00\x00\x00\x08\x7f"),
    ),  # TIMESTAMP_COL is system generated, NOT NULL
]


EXPECTED_UNICODE_TEST_DATA = [Row(編號=1, 姓名="山田太郎", 國家="日本", 備註="これはUnicodeテストです")]
