name: Snowpark pandas Changedoc Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main
    paths:
      - 'src/snowflake/snowpark/modin/**'

jobs:
  check_pandas_change_doc:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'NO-PANDAS-CHANGEDOC-UPDATES')}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Ensure Snowpark pandas docs is updated
      run: git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q "docs/source/modin"
