name: "GitHub PR Labeler"
description: 'Automatically label new pull requests based on the paths of files being changed'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - id: label-the-pr
      uses: actions/labeler@v5
