name: "Snowpark pandas PR Labeler"

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: label-the-pr
      uses: actions/labeler@v5
